[project]
name = "situantionship"
version = "0.1.0"
description = "Classificatore ironico dell'energia dei messaggi in italiano."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

dependencies = [
  "sentence-transformers",
  "numpy",
  "emoji",
  "fastapi",
  "uvicorn",
  "python-dotenv>=1.2.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
