name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Replace Firebase config script with inline config
        run: |
          # Read the current index.html and replace the firebase-config.js line with inline config
          cat index.html | sed 's|<script src="firebase-config.js"></script>|<script>\
          const firebaseConfig = {\
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",\
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",\
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",\
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",\
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",\
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",\
            appId: "${{ secrets.FIREBASE_APP_ID }}",\
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"\
          };\
          </script>|' > index_modified.html
          
          # Replace the original file
          mv index_modified.html index.html

      - name: Verify HTML modification
        run: |
          echo "=== Checking if Firebase config was injected ==="
          grep -A 5 -B 2 "const firebaseConfig" index.html || echo "Config not found in HTML"
          echo "=== Also checking if old script tag is gone ==="
          grep "firebase-config.js" index.html && echo "ERROR: Old script tag still present!" || echo "SUCCESS: Old script tag removed"

      - name: Install and Deploy
        run: |
          npm install
          npm install gh-pages --save-dev
          git config --global user.name 'Rkomi98'
          git config --global user.email 'mirko-98@libero.it'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npx gh-pages -d . -m "Deploy from GitHub Actions" 