name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Inject Firebase config into HTML
        run: |
          # Create a temporary Firebase config file
          cat > temp_firebase_config.js << 'EOF'
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          };
          EOF
          
          # Replace the script src line with inline script content, accounting for indentation
          awk '
          /^[[:space:]]*<script src="firebase-config.js"><\/script>/ {
            # Capture the indentation from the original line
            match($0, /^[[:space:]]*/);
            indent = substr($0, RSTART, RLENGTH);
            
            print indent "<script>"
            while ((getline line < "temp_firebase_config.js") > 0) {
              print indent "  " line
            }
            close("temp_firebase_config.js")
            print indent "</script>"
            next
          }
          { print }
          ' index.html > index_new.html
          
          # Replace the original file
          mv index_new.html index.html
          
          # Clean up
          rm temp_firebase_config.js

      - name: Verify HTML modification
        run: |
          echo "=== Checking if Firebase config was injected ==="
          grep -A 10 -B 2 "const firebaseConfig" index.html || echo "Config not found in HTML"

      - name: Install and Deploy
        run: |
          npm install
          npm install gh-pages --save-dev
          git config --global user.name 'Rkomi98'
          git config --global user.email 'mirko-98@libero.it'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npx gh-pages -d . -m "Deploy from GitHub Actions" 