name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Firebase config file
        run: |
          echo "const firebaseConfig = {" > firebase-config.js
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> firebase-config.js
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> firebase-config.js
          echo "  databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}'," >> firebase-config.js
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> firebase-config.js
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> firebase-config.js
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> firebase-config.js
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> firebase-config.js
          echo "  measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> firebase-config.js
          echo "};" >> firebase-config.js

      - name: Install and Deploy
        run: |
          npm install
          npm install gh-pages --save-dev
          git config --global user.name 'Rkomi98'
          git config --global user.email 'mirko-98@libero.it'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npx gh-pages -d . -m "Deploy from GitHub Actions" 